homeassistant:
  name: Home
  latitude: XXXXX
  longitude: XXXXX
  elevation: XXXXX
  unit_system: metric
  time_zone: XXXXX
  customize: !include customize.yaml
      
frontend:
  themes: !include themes.yaml

ios:

map:
    
history:

recorder:

group: !include groups.yaml

scene: !include scenes.yaml

script: !include scripts.yaml

automation: !include automations.yaml

automation old: !include automation.yaml

switch: !include switches.yaml

zone: !include zones.yaml
  
device_tracker: !include devices.yaml
  
notify: !include notify.yaml
  
sensor: !include sensors.yaml
        
cover: !include covers.yaml
      
media_player: !include players.yaml
    
config:

sun:

http:

  api_password: XXXXX
  base_url: XXXXX

tts:
  - platform: google
    language: en

#ifttt:
#  key: XXXXX

weather:
  - platform: darksky
    api_key: XXXXX
    update_interval:
      minutes: 10

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 60000
  
vacuum:
  - platform: xiaomi_miio
    host: XXXXX
    token: XXXXX
    
wemo:
  static:
    - XXXXX
    - XXXXX
    - XXXXX

google:
  client_id: XXXXX
  client_secret: XXXXX

light:
  - platform: group
    name: Dining Room Lights
    entities:
      - light.drp
      - light.drt
    
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kr
      - light.kl
 
hue:
  bridges:
    - host: XXXXX
      allow_unreachable: true

input_number: 
  alarmhour:
    name: Hour
    icon: mdi:timer
    initial: 6
    min: 0
    max: 23
    step: 1
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 0
    min: 0
    max: 55
    step: 5
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
    
input_select:
  vacuum_speed:
    name: Set Speed
    options:
      - Quiet
      - Balanced
      - Turbo
      - Max
    initial: Turbo
    icon: mdi:robot-vacuum
  vacuum_room:
    name: Select Area
    options:
      - Entrance
      - Bedroom
      - Dining Room
      - Kitchen
      - Lounge Room
      - Baby's Room
      - Hallway, Laundry, and Bathroom
      - Elliott's Room
    initial: Bedroom
    icon: mdi:robot-vacuum
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Bagel
      - Riverdance
      - Classical
      - Christmas
      - Rock
      - Newski
      - Discover Billy
      - Bowls Club 2028
      - Hamilton
      - Elliott
      - Indie
    icon: mdi:spotify
  spotify_source:
    name: 'Source:'
    options:
      - Lounge Room
      - Bedroom
      - Patio
    initial: Lounge Room
    icon: mdi:speaker-wireless
  alexa:
    name: Alexa
    options:
      - None
      - Lounge Room
      - Bedroom
      - Patio
    initial: None
    icon: mdi:target

input_text:
  alexa_tts:
    name: Alexa TTS
    initial: Hello
    
input_boolean: 
  alarmstatus:
    name: Wake Me Up
    initial: off
    icon: mdi:alarm-check
  alarmweekday:
    name: Weekdays Only
    initial: off
    icon: mdi:calendar
  elliott_tv:
    name: Kid's TV
    initial: off
    icon: mdi:theater
  bedroom_lights:
    name: Bedroom Lights
    initial: off
    icon: mdi:lightbulb
  bedrom_music:
    name: Bedroom Music
    initial: off
    icon: mdi:music-circle